# Generated by Django 4.2 on 2023-04-15 07:21

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VpnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('countryshorts', django_countries.fields.CountryField(max_length=2)),
                ('username', models.CharField(max_length=100)),
                ('pasword', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enable', models.BooleanField(default=True)),
                ('config', models.TextField()),
            ],
        ),
    ]
