# Generated by Django 4.2 on 2023-04-15 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VpnApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applogo', models.ImageField(upload_to='ApplicationLogo/')),
                ('appname', models.CharField(max_length=100)),
                ('packagename', models.CharField(max_length=100)),
                ('vpnserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VpnApi.vpnmodel')),
            ],
        ),
    ]
