# Generated by Django 4.2 on 2023-04-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VpnApi', '0002_applicationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=100)),
                ('fullName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='vpnmodel',
            name='countryshorts',
            field=models.CharField(max_length=100),
        ),
    ]
