# Generated by Django 4.2 on 2023-04-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VpnApi', '0004_alter_applicationmodel_vpnserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='vpnserver',
            field=models.CharField(max_length=250),
        ),
    ]
